server:
  port: 8080

spring:
  application:
    name: login-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

login:
  ttlMillis: 600000
